### ISSUE TITLE
Can not found certs directory at first run

### ISSUE THREAD

**Issue by ardaguclu** [CanonicalLtd/iot-devicetwin#1]
When I want to run by following the steps at readme, it returns an error;

`Error generating encryption secret: open certs/.secret: no such file or directory`

I suppose we should first call .gencerts.sh before running devicetwin, since we have not already any certificates retrieved from repo or somewhere else.

**Comment by slimjim777** [comment]
There are a number of setup steps involved in deploying this service, and it needs the management and identity services to be useful. There is a white paper being written to cover the installation and configuration steps, but that is still being reviewed. I'll link to that in the readme when that is published.
